// Talentree.Service/Mapping/MappingProfile.cs

using AutoMapper;
using Talentree.Core.Entities.Identity;
using Talentree.Service.DTOs.Auth;

namespace Talentree.Service.Mapping
{
    /// <summary>
    /// AutoMapper configuration for entity-DTO mappings
    /// </summary>
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            // ═══════════════════════════════════════════════════════════
            // AUTHENTICATION MAPPINGS
            // ═══════════════════════════════════════════════════════════

            // ───────────────────────────────────────────────────────────
            // AppUser → UserInfoDto (for responses)
            // ───────────────────────────────────────────────────────────
            CreateMap<AppUser, UserInfoDto>()
                .ForMember(dest => dest.Id,
                    opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.DisplayName,
                    opt => opt.MapFrom(src => src.DisplayName))
                .ForMember(dest => dest.Email,
                    opt => opt.MapFrom(src => src.Email ?? string.Empty))
                .ForMember(dest => dest.PhoneNumber,
                    opt => opt.MapFrom(src => src.PhoneNumber))
                .ForMember(dest => dest.IsEmailVerified,
                    opt => opt.MapFrom(src => src.EmailConfirmed))
                .ForMember(dest => dest.IsActive,
                    opt => opt.MapFrom(src => src.IsActive))
                .ForMember(dest => dest.CreatedAt,
                    opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.Roles,
                    opt => opt.Ignore()); // Will be set manually in service

            // ───────────────────────────────────────────────────────────
            // RegisterDto → AppUser (for registration)
            // ───────────────────────────────────────────────────────────
            CreateMap<RegisterDto, AppUser>()
                .ForMember(dest => dest.DisplayName,
                    opt => opt.MapFrom(src => $"{src.FirstName} {src.LastName}".Trim()))
                .ForMember(dest => dest.Email,
                    opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.UserName,
                    opt => opt.MapFrom(src => src.Email)) // Email as username
                .ForMember(dest => dest.PhoneNumber,
                    opt => opt.MapFrom(src => src.PhoneNumber))
                .ForMember(dest => dest.IsActive,
                    opt => opt.MapFrom(src => true))
                .ForMember(dest => dest.EmailConfirmed,
                    opt => opt.MapFrom(src => false)) // Must verify email first
                .ForMember(dest => dest.CreatedAt,
                    opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.Id,
                    opt => opt.Ignore()) // Generated by Identity
                .ForMember(dest => dest.NormalizedEmail,
                    opt => opt.Ignore()) // Set by Identity
                .ForMember(dest => dest.NormalizedUserName,
                    opt => opt.Ignore()) // Set by Identity
                .ForMember(dest => dest.PasswordHash,
                    opt => opt.Ignore()) // Set by UserManager
                .ForMember(dest => dest.SecurityStamp,
                    opt => opt.Ignore()) // Set by Identity
                .ForMember(dest => dest.ConcurrencyStamp,
                    opt => opt.Ignore()) // Set by Identity
                .ForMember(dest => dest.EmailConfirmed,
                    opt => opt.Ignore()) // Will be set after OTP verification
                .ForMember(dest => dest.PhoneNumberConfirmed,
                    opt => opt.Ignore())
                .ForMember(dest => dest.TwoFactorEnabled,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LockoutEnabled,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LockoutEnd,
                    opt => opt.Ignore())
                .ForMember(dest => dest.AccessFailedCount,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LastLoginAt,
                    opt => opt.Ignore())
                .ForMember(dest => dest.Address,
                    opt => opt.Ignore())
                .ForMember(dest => dest.BusinessOwnerProfile,
                    opt => opt.Ignore());

            // ═══════════════════════════════════════════════════════════
            // FUTURE MAPPINGS (Products, Orders....
            // ═══════════════════════════════════════════════════════════

            // Product mappings will go here
            // CreateMap<Product, ProductDto>();

            // Order mappings will go here
            // CreateMap<Order, OrderDto>();
        }
    }
}