// Talentree.Service/Mapping/MappingProfile.cs

using AutoMapper;
using Talentree.Core.Entities;
using Talentree.Core.Entities.Identity;
using Talentree.Core.Enums;
using Talentree.Service.DTOs.Admin;
using Talentree.Service.DTOs.Admin.Product;
using Talentree.Service.DTOs.Admin.RawMaterial;
using Talentree.Service.DTOs.Admin.Supplier;
using Talentree.Service.DTOs.Auth;
using Talentree.Service.DTOs.Basket;
using Talentree.Service.DTOs.BoProductionRequest;
using Talentree.Service.DTOs.MaterialOrder;
using Talentree.Service.DTOs.Notification;
using Talentree.Service.DTOs.Payout;
using Talentree.Service.DTOs.Products;
using Talentree.Service.DTOs.RawMaterial;
using Talentree.Service.DTOs.Support;
using Talentree.Service.DTOs.Transaction;
using Talentree.Service.DTOs.UserManagement;

namespace Talentree.Service.Mapping
{
    /// <summary>
    /// AutoMapper configuration for entity-DTO mappings
    /// </summary>
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            // ═══════════════════════════════════════════════════════════
            // AUTHENTICATION MAPPINGS
            // ═══════════════════════════════════════════════════════════

            // ───────────────────────────────────────────────────────────
            // AppUser → UserInfoDto (for responses)
            // ───────────────────────────────────────────────────────────
            CreateMap<AppUser, UserInfoDto>()
                .ForMember(dest => dest.Id,
                    opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.DisplayName,
                    opt => opt.MapFrom(src => src.DisplayName))
                .ForMember(dest => dest.Email,
                    opt => opt.MapFrom(src => src.Email ?? string.Empty))
                .ForMember(dest => dest.PhoneNumber,
                    opt => opt.MapFrom(src => src.PhoneNumber))
                .ForMember(dest => dest.IsEmailVerified,
                    opt => opt.MapFrom(src => src.EmailConfirmed))
                .ForMember(dest => dest.IsActive,
                    opt => opt.MapFrom(src => src.IsActive))
                .ForMember(dest => dest.CreatedAt,
                    opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.Roles,
                    opt => opt.Ignore()); // Will be set manually in service

            // ───────────────────────────────────────────────────────────
            // RegisterDto → AppUser (for registration)
            // ───────────────────────────────────────────────────────────
            CreateMap<RegisterDto, AppUser>()
                .ForMember(dest => dest.DisplayName,
                    opt => opt.MapFrom(src => $"{src.FirstName} {src.LastName}".Trim()))
                .ForMember(dest => dest.Email,
                    opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.UserName,
                    opt => opt.MapFrom(src => src.Email)) // Email as username
                .ForMember(dest => dest.PhoneNumber,
                    opt => opt.MapFrom(src => src.PhoneNumber))
                .ForMember(dest => dest.IsActive,
                    opt => opt.MapFrom(src => true))
                .ForMember(dest => dest.EmailConfirmed,
                    opt => opt.MapFrom(src => false)) // Must verify email first
                .ForMember(dest => dest.CreatedAt,
                    opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.Id,
                    opt => opt.Ignore()) // Generated by Identity
                .ForMember(dest => dest.NormalizedEmail,
                    opt => opt.Ignore()) // Set by Identity
                .ForMember(dest => dest.NormalizedUserName,
                    opt => opt.Ignore()) // Set by Identity
                .ForMember(dest => dest.PasswordHash,
                    opt => opt.Ignore()) // Set by UserManager
                .ForMember(dest => dest.SecurityStamp,
                    opt => opt.Ignore()) // Set by Identity
                .ForMember(dest => dest.ConcurrencyStamp,
                    opt => opt.Ignore()) // Set by Identity
                .ForMember(dest => dest.EmailConfirmed,
                    opt => opt.Ignore()) // Will be set after OTP verification
                .ForMember(dest => dest.PhoneNumberConfirmed,
                    opt => opt.Ignore())
                .ForMember(dest => dest.TwoFactorEnabled,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LockoutEnabled,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LockoutEnd,
                    opt => opt.Ignore())
                .ForMember(dest => dest.AccessFailedCount,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LastLoginAt,
                    opt => opt.Ignore())
                .ForMember(dest => dest.Address,
                    opt => opt.Ignore())
                .ForMember(dest => dest.BusinessOwnerProfile,
                    opt => opt.Ignore());
            // ═══════════════════════════════════════════════════════════
            // BusinessOwnerRegisterDto → AppUser
            // ═══════════════════════════════════════════════════════════
            CreateMap<BusinessOwnerRegisterDto, AppUser>()
                .ForMember(dest => dest.DisplayName,
                    opt => opt.MapFrom(src => $"{src.FirstName} {src.LastName}".Trim()))
                .ForMember(dest => dest.Email,
                    opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.UserName,
                    opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.PhoneNumber,
                    opt => opt.MapFrom(src => src.PhoneNumber))
                .ForMember(dest => dest.IsActive,
                    opt => opt.MapFrom(src => true))
                .ForMember(dest => dest.EmailConfirmed,
                    opt => opt.MapFrom(src => false))
                .ForMember(dest => dest.CreatedAt,
                    opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.Id,
                    opt => opt.Ignore())
                .ForMember(dest => dest.NormalizedEmail,
                    opt => opt.Ignore())
                .ForMember(dest => dest.NormalizedUserName,
                    opt => opt.Ignore())
                .ForMember(dest => dest.PasswordHash,
                    opt => opt.Ignore())
                .ForMember(dest => dest.SecurityStamp,
                    opt => opt.Ignore())
                .ForMember(dest => dest.ConcurrencyStamp,
                    opt => opt.Ignore())
                .ForMember(dest => dest.EmailConfirmed,
                    opt => opt.Ignore())
                .ForMember(dest => dest.PhoneNumberConfirmed,
                    opt => opt.Ignore())
                .ForMember(dest => dest.TwoFactorEnabled,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LockoutEnabled,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LockoutEnd,
                    opt => opt.Ignore())
                .ForMember(dest => dest.AccessFailedCount,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LastLoginAt,
                    opt => opt.Ignore())
                .ForMember(dest => dest.Address,
                    opt => opt.Ignore())
                .ForMember(dest => dest.BusinessOwnerProfile,
                    opt => opt.Ignore());

            // ═══════════════════════════════════════════════════════════
            // BusinessOwnerRegisterDto → BusinessOwnerProfile
            // ═══════════════════════════════════════════════════════════
            CreateMap<BusinessOwnerRegisterDto, BusinessOwnerProfile>()
                .ForMember(dest => dest.BusinessName,
                    opt => opt.MapFrom(src => src.BusinessName))
                .ForMember(dest => dest.BusinessCategory,
                    opt => opt.MapFrom(src => src.BusinessCategory))
                .ForMember(dest => dest.BusinessDescription,
                    opt => opt.MapFrom(src => src.BusinessDescription))
                .ForMember(dest => dest.BusinessAddress,
                    opt => opt.MapFrom(src => src.BusinessAddress))
                .ForMember(dest => dest.TaxId,
                    opt => opt.MapFrom(src => src.TaxId))
                .ForMember(dest => dest.FacebookLink,
                    opt => opt.MapFrom(src => src.FacebookLink))
                .ForMember(dest => dest.InstagramLink,
                    opt => opt.MapFrom(src => src.InstagramLink))
                .ForMember(dest => dest.WebsiteLink,
                    opt => opt.MapFrom(src => src.WebsiteLink))
                .ForMember(dest => dest.Status,
                    opt => opt.MapFrom(src => ApprovalStatus.Pending))
                .ForMember(dest => dest.AutoApprovalDeadline,
                    opt => opt.MapFrom(src => DateTime.UtcNow.AddHours(12)))
                .ForMember(dest => dest.CreatedAt,
                    opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.Id,
                    opt => opt.Ignore())
                .ForMember(dest => dest.UserId,
                    opt => opt.Ignore())
                .ForMember(dest => dest.ApprovedAt,
                    opt => opt.Ignore())
                .ForMember(dest => dest.ApprovedBy,
                    opt => opt.Ignore())
                .ForMember(dest => dest.RejectionReason,
                    opt => opt.Ignore())
                .ForMember(dest => dest.User,
                    opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt,
                    opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedBy,
                    opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted,
                    opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt,
                    opt => opt.Ignore())
                .ForMember(dest => dest.CreatedBy,
                    opt => opt.Ignore());



            // ───────────────────────────────────────────────────────────
            // BusinessOwnerProfile → PendingBusinessOwnerDto
            // ───────────────────────────────────────────────────────────
            CreateMap<BusinessOwnerProfile, BusinessOwnerApplicationDto>()
                // IDs
                .ForMember(d => d.ProfileId, o => o.MapFrom(s => s.Id))
                .ForMember(d => d.UserId, o => o.MapFrom(s => s.UserId))

                // Owner info (from AppUser)
                .ForMember(d => d.OwnerName, o => o.MapFrom(s => s.User.DisplayName))
                .ForMember(d => d.Email, o => o.MapFrom(s => s.User.Email ?? string.Empty))
                .ForMember(d => d.PhoneNumber, o => o.MapFrom(s => s.User.PhoneNumber ?? string.Empty))

                // Business info
                .ForMember(d => d.BusinessName, o => o.MapFrom(s => s.BusinessName))
                .ForMember(d => d.BusinessCategory, o => o.MapFrom(s => s.BusinessCategory))
                .ForMember(d => d.BusinessDescription, o => o.MapFrom(s => s.BusinessDescription))
                .ForMember(d => d.BusinessAddress, o => o.MapFrom(s => s.BusinessAddress))
                .ForMember(d => d.TaxId, o => o.MapFrom(s => s.TaxId))

                // Social links
                .ForMember(d => d.FacebookLink, o => o.MapFrom(s => s.FacebookLink))
                .ForMember(d => d.InstagramLink, o => o.MapFrom(s => s.InstagramLink))
                .ForMember(d => d.WebsiteLink, o => o.MapFrom(s => s.WebsiteLink))
                // ⭐ Approval Status
                .ForMember(d => d.Status, o => o.MapFrom(s => s.Status))
                .ForMember(d => d.StatusText, o => o.MapFrom(s => s.Status.ToString()))
                .ForMember(d => d.ApprovedAt, o => o.MapFrom(s => s.ApprovedAt))
                .ForMember(d => d.ApprovedBy, o => o.MapFrom(s => s.ApprovedBy))
                .ForMember(d => d.RejectionReason, o => o.MapFrom(s => s.RejectionReason))

                // Dates
                .ForMember(d => d.SubmittedAt, o => o.MapFrom(s => s.CreatedAt))
                .ForMember(d => d.AutoApprovalDeadline, o => o.MapFrom(s => s.AutoApprovalDeadline))

                // Calculated fields
                .ForMember(
                    d => d.WillAutoApprove,
                    o => o.MapFrom(s =>
                        s.Status == ApprovalStatus.Pending &&
                        s.AutoApprovalDeadline.HasValue &&
                        s.AutoApprovalDeadline.Value > DateTime.UtcNow
                    )
                )
                .ForMember(
                    d => d.TimeUntilAutoApproval,
                    o => o.MapFrom(s =>
                        s.Status == ApprovalStatus.Pending &&
                        s.AutoApprovalDeadline.HasValue &&
                        s.AutoApprovalDeadline.Value > DateTime.UtcNow
                            ? s.AutoApprovalDeadline.Value - DateTime.UtcNow
                            : (TimeSpan?)null
                    )
                );

            // ───────────────────────────────────────────────────────────
            // RAW MATERIAL MAPPINGS
            // ───────────────────────────────────────────────────────────

            // RawMaterial → RawMaterialDto (BO-facing store)
            CreateMap<RawMaterial, RawMaterialDto>()
                .ForMember(dest => dest.SupplierName,
                    opt => opt.MapFrom(src => src.Supplier != null ? src.Supplier.Name : string.Empty));

            // RawMaterial → AdminRawMaterialDto (admin panel)
            CreateMap<RawMaterial, AdminRawMaterialDto>()
                .ForMember(dest => dest.SupplierName,
                    opt => opt.MapFrom(src => src.Supplier != null ? src.Supplier.Name : string.Empty));

            // CreateRawMaterialDto → RawMaterial (admin create)
            // IsAvailable is set manually in service based on StockQuantity
            CreateMap<CreateRawMaterialDto, RawMaterial>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.IsAvailable, opt => opt.Ignore())
                .ForMember(dest => dest.Supplier, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedBy, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore());

            // ───────────────────────────────────────────────────────────
            // SUPPLIER MAPPINGS
            // ───────────────────────────────────────────────────────────

            // Supplier → SupplierDto
            CreateMap<Supplier, SupplierDto>()
                .ForMember(dest => dest.MaterialCount,
                    opt => opt.MapFrom(src =>
                        src.RawMaterials != null
                            ? src.RawMaterials.Count(m => !m.IsDeleted)
                            : 0));

            // CreateSupplierDto → Supplier
            // IsActive is set manually in service
            CreateMap<CreateSupplierDto, Supplier>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.IsActive, opt => opt.Ignore())
                .ForMember(dest => dest.RawMaterials, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedBy, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore());

            // ───────────────────────────────────────────────────────────
            // BASKET MAPPINGS
            // ───────────────────────────────────────────────────────────

            // MaterialBasketItem → MaterialBasketItemDto
            CreateMap<MaterialBasketItem, MaterialBasketItemDto>()
                .ForMember(dest => dest.MaterialName,
                    opt => opt.MapFrom(src => src.RawMaterial != null ? src.RawMaterial.Name : string.Empty))
                .ForMember(dest => dest.PictureUrl,
                    opt => opt.MapFrom(src => src.RawMaterial != null ? src.RawMaterial.PictureUrl : null))
                .ForMember(dest => dest.Unit,
                    opt => opt.MapFrom(src => src.RawMaterial != null ? src.RawMaterial.Unit : string.Empty))
                .ForMember(dest => dest.SupplierName,
                    opt => opt.MapFrom(src => src.RawMaterial != null && src.RawMaterial.Supplier != null
                        ? src.RawMaterial.Supplier.Name
                        : string.Empty))
                .ForMember(dest => dest.UnitPrice,
                    opt => opt.MapFrom(src => src.RawMaterial != null ? src.RawMaterial.Price : 0))
                .ForMember(dest => dest.MinimumOrderQuantity,
                    opt => opt.MapFrom(src => src.RawMaterial != null ? src.RawMaterial.MinimumOrderQuantity : 1))
                // LineTotal is a computed property on the DTO — AutoMapper resolves it automatically
                .ForMember(dest => dest.LineTotal, opt => opt.Ignore());

            // MaterialBasket → MaterialBasketDto
            // Subtotal and TotalItemCount are computed from Items — AutoMapper resolves them automatically
            CreateMap<MaterialBasket, MaterialBasketDto>()
                .ForMember(dest => dest.Subtotal, opt => opt.Ignore())
                .ForMember(dest => dest.TotalItemCount, opt => opt.Ignore());


            // ProductImage → ProductImageDto
            CreateMap<ProductImage, ProductImageDto>();

            // Product → ProductDto
            CreateMap<Product, ProductDto>()
                .ForMember(d => d.StatusText,
                    o => o.MapFrom(s => s.Status.ToString()))
                .ForMember(d => d.CategoryName,
                    o => o.MapFrom(s => s.Category != null ? s.Category.Name : string.Empty))
                .ForMember(d => d.MainImageUrl,
                    o => o.MapFrom(s =>
                    s.Images != null && s.Images.Any()
                    ? s.Images.FirstOrDefault(i => i.IsMain) != null
                        ? s.Images.First(i => i.IsMain).ImageUrl
                            : s.Images.OrderBy(i => i.SortOrder).First().ImageUrl
                                                                                : null))
                .ForMember(d => d.Images,
                    o => o.MapFrom(s =>
                         s.Images != null
                            ? s.Images.OrderBy(i => i.SortOrder).ToList()
                                : new List<ProductImage>()));




            // ═══════════════════════════════════════════════════════════
            // NOTIFICATION MAPPINGS
            // ═══════════════════════════════════════════════════════════

            CreateMap<Notification, NotificationDto>()
                .ForMember(dest => dest.TypeText,
                    opt => opt.MapFrom(src => src.Type.ToString()))
                .ForMember(dest => dest.PriorityText,
                    opt => opt.MapFrom(src => src.Priority.ToString()))
                .ForMember(dest => dest.TimeAgo,
                    opt => opt.MapFrom(src => GetTimeAgo(src.CreatedAt)));

            CreateMap<CreateNotificationDto, Notification>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // ═══════════════════════════════════════════════════════════
            // NOTIFICATION PREFERENCE MAPPINGS
            // ═══════════════════════════════════════════════════════════

            CreateMap<NotificationPreference, NotificationPreferenceDto>();

            CreateMap<UpdateNotificationPreferenceDto, NotificationPreference>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));



            CreateMap<Product, PendingProductDto>()
                .ForMember(dest => dest.CategoryName,
                    opt => opt.MapFrom(src => src.Category.Name))
                .ForMember(dest => dest.BusinessOwnerName,
                    opt => opt.MapFrom(src => src.BusinessOwner.User.DisplayName))
                .ForMember(dest => dest.BusinessName,
                    opt => opt.MapFrom(src => src.BusinessOwner.BusinessName))
                .ForMember(dest => dest.MainImageUrl,
                    opt => opt.MapFrom(src =>
                        src.Images.FirstOrDefault(i => i.IsMain) != null
                            ? src.Images.First(i => i.IsMain).ImageUrl
                            : src.Images.OrderBy(i => i.SortOrder).FirstOrDefault() != null
                                ? src.Images.OrderBy(i => i.SortOrder).First().ImageUrl
                                : null))
                .ForMember(dest => dest.ImageCount,
                    opt => opt.MapFrom(src => src.Images.Count))
                .ForMember(dest => dest.StatusText,
                    opt => opt.MapFrom(src => src.Status.ToString()))
                .ForMember(dest => dest.TimeAgo,
                    opt => opt.MapFrom(src => GetTimeAgo(src.CreatedAt)));

            // ═══════════════════════════════════════════════════════════
            // MATERIAL ORDER
            // ═══════════════════════════════════════════════════════════

            // ───────────────────────────────────────────────────────────
            // MaterialOrder → MaterialOrderSummaryDto
            // DeliveryLocation is computed from City + Country.
            // ItemCount is derived from the Items collection.
            // ───────────────────────────────────────────────────────────
            CreateMap<MaterialOrder, MaterialOrderSummaryDto>()
                .ForMember(dest => dest.ItemCount,
                    opt => opt.MapFrom(src => src.Items.Count))
                .ForMember(dest => dest.DeliveryLocation,
                    opt => opt.MapFrom(src => $"{src.DeliveryCity}, {src.DeliveryCountry}"));

            // ───────────────────────────────────────────────────────────
            // MaterialOrder → MaterialOrderDto (full detail)
            // All scalar properties map by convention.
            // Items are mapped via MaterialOrderItem → MaterialOrderItemDto below.
            // ───────────────────────────────────────────────────────────
            CreateMap<MaterialOrder, MaterialOrderDto>();

            // ───────────────────────────────────────────────────────────
            // MaterialOrderItem → MaterialOrderItemDto
            // MaterialName and Unit are resolved from the loaded RawMaterial navigation.
            // LineTotal is a computed property on the entity — mapped directly.
            // ───────────────────────────────────────────────────────────
            CreateMap<MaterialOrderItem, MaterialOrderItemDto>()
                .ForMember(dest => dest.MaterialName,
                    opt => opt.MapFrom(src =>
                        src.RawMaterial != null ? src.RawMaterial.Name : string.Empty))
                .ForMember(dest => dest.Unit,
                    opt => opt.MapFrom(src =>
                        src.RawMaterial != null ? src.RawMaterial.Unit : string.Empty))
                .ForMember(dest => dest.LineTotal,
                    opt => opt.MapFrom(src => src.LineTotal));

            // ═══════════════════════════════════════════════════════════
            // PRODUCTION REQUESTS
            // ═══════════════════════════════════════════════════════════

            // ───────────────────────────────────────────────────────────
            // BoProductionRequest → ProductionRequestSummaryDto
            // ItemCount is derived from the Items collection.
            // ───────────────────────────────────────────────────────────
            CreateMap<BoProductionRequest, ProductionRequestSummaryDto>()
                .ForMember(dest => dest.ItemCount,
                    opt => opt.MapFrom(src => src.Items.Count));

            // ───────────────────────────────────────────────────────────
            // BoProductionRequest → ProductionRequestDetailDto
            // All scalar properties map by convention.
            // Items and StatusHistory are mapped via their own CreateMap calls below.
            // ───────────────────────────────────────────────────────────
            CreateMap<BoProductionRequest, ProductionRequestDetailDto>();

            // ───────────────────────────────────────────────────────────
            // BoProductionRequestItem → ProductionRequestItemDetailDto
            // PreferredRawMaterialName is resolved from the navigation property.
            // ───────────────────────────────────────────────────────────
            CreateMap<BoProductionRequestItem, ProductionRequestItemDetailDto>()
                .ForMember(dest => dest.PreferredRawMaterialName,
                    opt => opt.MapFrom(src =>
                        src.PreferredRawMaterial != null ? src.PreferredRawMaterial.Name : null));

            // ───────────────────────────────────────────────────────────
            // BoProductionRequestStatusHistory → ProductionRequestHistoryDto
            // ChangedAt maps from CreatedAt (set by BaseEntity on insert).
            // ───────────────────────────────────────────────────────────
            CreateMap<BoProductionRequestStatusHistory, ProductionRequestHistoryDto>()
                .ForMember(dest => dest.ChangedAt,
                    opt => opt.MapFrom(src => src.CreatedAt));


            // ═══════════════════════════════════════════════════════════
            // SUPPORT TICKET MAPPINGS
            // ═══════════════════════════════════════════════════════════

            CreateMap<SupportTicket, TicketDto>()
                .ForMember(dest => dest.CategoryText,
                    opt => opt.MapFrom(src => src.Category.ToString()))
                .ForMember(dest => dest.StatusText,
                    opt => opt.MapFrom(src => src.Status.ToString()))
                .ForMember(dest => dest.PriorityText,
                    opt => opt.MapFrom(src => src.Priority.ToString()))
                .ForMember(dest => dest.BusinessOwnerName,
                    opt => opt.MapFrom(src => src.BusinessOwner.DisplayName))
                .ForMember(dest => dest.BusinessOwnerEmail,
                    opt => opt.MapFrom(src => src.BusinessOwner.Email))
                .ForMember(dest => dest.MessageCount,
                    opt => opt.MapFrom(src => src.Messages.Count))
                .ForMember(dest => dest.AttachmentCount,
                    opt => opt.MapFrom(src => src.Attachments.Count))
                .ForMember(dest => dest.TimeAgo,
                    opt => opt.MapFrom(src => GetTimeAgo(src.CreatedAt)));

            CreateMap<SupportTicket, TicketListItemDto>()
                .ForMember(dest => dest.CategoryText,
                    opt => opt.MapFrom(src => src.Category.ToString()))
                .ForMember(dest => dest.StatusText,
                    opt => opt.MapFrom(src => src.Status.ToString()))
                .ForMember(dest => dest.PriorityText,
                    opt => opt.MapFrom(src => src.Priority.ToString()))
                .ForMember(dest => dest.MessageCount,
                    opt => opt.MapFrom(src => src.Messages.Count))
                .ForMember(dest => dest.HasUnreadMessages,
                    opt => opt.MapFrom(src => false)) // TODO: implement
                .ForMember(dest => dest.TimeAgo,
                    opt => opt.MapFrom(src => GetTimeAgo(src.CreatedAt)));

            CreateMap<TicketMessage, TicketMessageDto>()
                .ForMember(dest => dest.SenderName,
                    opt => opt.MapFrom(src => src.Sender.DisplayName))
                .ForMember(dest => dest.TimeAgo,
                    opt => opt.MapFrom(src => GetTimeAgo(src.CreatedAt)));

            CreateMap<TicketAttachment, TicketAttachmentDto>()
                .ForMember(dest => dest.FileSizeMB,
                    opt => opt.MapFrom(src => $"{src.FileSizeBytes / 1024.0 / 1024.0:F2} MB"));

            CreateMap<FAQ, FAQDto>();

            // Transaction → TransactionDto
            CreateMap<Transaction, TransactionDto>();

            CreateMap<PayoutRequest, PayoutRequestDto>()
                .ForMember(dest => dest.MaskedAccountIdentifier,
                    opt => opt.MapFrom(src =>
                        src.AccountIdentifierEnc != null && src.AccountIdentifierEnc.Length >= 4
                            ? "****" + src.AccountIdentifierEnc.Substring(src.AccountIdentifierEnc.Length - 4)
                            : "****"));


            CreateMap<AppUser, BusinessOwnerListDto>()
               .ForMember(dest => dest.BusinessName,
                   opt => opt.MapFrom(src => src.BusinessOwnerProfile!.BusinessName))
               .ForMember(dest => dest.OwnerName,
                   opt => opt.MapFrom(src => src.DisplayName))
               .ForMember(dest => dest.Email,
                   opt => opt.MapFrom(src => src.Email))
               .ForMember(dest => dest.Category,
                   opt => opt.MapFrom(src => src.BusinessOwnerProfile!.BusinessCategory))
               .ForMember(dest => dest.ApprovalStatus,
                   opt => opt.MapFrom(src => src.BusinessOwnerProfile!.Status))
               .ForMember(dest => dest.ApprovalStatusText,
                   opt => opt.MapFrom(src => src.BusinessOwnerProfile!.Status.ToString()))
               .ForMember(dest => dest.AccountStatus,
                   opt => opt.MapFrom(src => src.AccountStatus))
               .ForMember(dest => dest.AccountStatusText,
                   opt => opt.MapFrom(src => src.AccountStatus.ToString()))
               .ForMember(dest => dest.RegistrationDate,
                   opt => opt.MapFrom(src => src.CreatedAt))
               .ForMember(dest => dest.LastLoginAt,
                   opt => opt.MapFrom(src => src.LastLoginAt))
               .ForMember(dest => dest.IsSuspended,
                   opt => opt.MapFrom(src => src.AccountStatus == AccountStatus.Suspended))
               .ForMember(dest => dest.IsBanned,
                   opt => opt.MapFrom(src => src.AccountStatus == AccountStatus.Banned))
               .ForMember(dest => dest.IsBlocked,
                   opt => opt.MapFrom(src => src.IsBlocked))
               .ForMember(dest => dest.TotalProducts, opt => opt.Ignore())
               .ForMember(dest => dest.TotalOrders, opt => opt.Ignore())
               .ForMember(dest => dest.TotalRevenue, opt => opt.Ignore());

            CreateMap<AppUser, BusinessOwnerDetailsDto>()
                .ForMember(dest => dest.BusinessName,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.BusinessName))
                .ForMember(dest => dest.BusinessDescription,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.BusinessDescription))
                .ForMember(dest => dest.BusinessCategory,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.BusinessCategory))
                .ForMember(dest => dest.BusinessAddress,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.BusinessAddress))
                .ForMember(dest => dest.TaxId,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.TaxId))
                .ForMember(dest => dest.ProfilePhotoUrl,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.ProfilePhotoUrl))
                .ForMember(dest => dest.BusinessLogoUrl,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.BusinessLogoUrl))
                .ForMember(dest => dest.FacebookLink,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.FacebookLink))
                .ForMember(dest => dest.InstagramLink,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.InstagramLink))
                .ForMember(dest => dest.WebsiteLink,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.WebsiteLink))
                .ForMember(dest => dest.ApprovalStatus,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.Status))
                .ForMember(dest => dest.ApprovalStatusText,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.Status.ToString()))
                .ForMember(dest => dest.AccountStatus,
                    opt => opt.MapFrom(src => src.AccountStatus))
                .ForMember(dest => dest.AccountStatusText,
                    opt => opt.MapFrom(src => src.AccountStatus.ToString()))
                .ForMember(dest => dest.ApprovedAt,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.ApprovedAt))
                .ForMember(dest => dest.ApprovedBy,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.ApprovedBy))
                .ForMember(dest => dest.RejectionReason,
                    opt => opt.MapFrom(src => src.BusinessOwnerProfile!.RejectionReason))
                .ForMember(dest => dest.RegistrationDate,
                    opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.TotalProducts, opt => opt.Ignore())
                .ForMember(dest => dest.TotalOrders, opt => opt.Ignore())
                .ForMember(dest => dest.TotalRevenue, opt => opt.Ignore())
                .ForMember(dest => dest.ComplaintCount, opt => opt.Ignore())
                .ForMember(dest => dest.ActionLogs, opt => opt.Ignore());

            CreateMap<AppUser, CustomerListDto>()
                .ForMember(dest => dest.Name,
                    opt => opt.MapFrom(src => src.DisplayName))
                .ForMember(dest => dest.RegistrationDate,
                    opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.AccountStatusText,
                    opt => opt.MapFrom(src => src.AccountStatus.ToString()))
                .ForMember(dest => dest.TotalOrders, opt => opt.Ignore())
                .ForMember(dest => dest.TotalSpent, opt => opt.Ignore());

            CreateMap<AppUser, CustomerDetailsDto>()
                .ForMember(dest => dest.Name,
                    opt => opt.MapFrom(src => src.DisplayName))
                .ForMember(dest => dest.ProfilePhotoUrl,
                    opt => opt.MapFrom(src => src.ProfilePhotoUrl))
                .ForMember(dest => dest.RegistrationDate,
                    opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.AccountStatusText,
                    opt => opt.MapFrom(src => src.AccountStatus.ToString()))
                .ForMember(dest => dest.TotalOrders, opt => opt.Ignore())
                .ForMember(dest => dest.TotalSpent, opt => opt.Ignore())
                .ForMember(dest => dest.TotalReviews, opt => opt.Ignore())
                .ForMember(dest => dest.ActionLogs, opt => opt.Ignore());

            CreateMap<UserActionLog, UserActionLogDto>()
                .ForMember(dest => dest.AdminName,
                    opt => opt.MapFrom(src => src.Admin.DisplayName))
                .ForMember(dest => dest.AdminEmail,
                    opt => opt.MapFrom(src => src.Admin.Email));

            CreateMap<Complaint, ComplaintDto>()
                .ForMember(dest => dest.ReportedUserName,
                    opt => opt.MapFrom(src => src.ReportedUser.DisplayName))
                .ForMember(dest => dest.ReportedUserEmail,
                    opt => opt.MapFrom(src => src.ReportedUser.Email))
                .ForMember(dest => dest.ReportedByName,
                    opt => opt.MapFrom(src => src.ReportedBy.DisplayName))
                .ForMember(dest => dest.ViolationTypeText,
                    opt => opt.MapFrom(src => src.ViolationType.ToString()))
                .ForMember(dest => dest.StatusText,
                    opt => opt.MapFrom(src => src.Status.ToString()));

        }




        // <summary>
        /// Calculate human-readable time ago
        /// </summary>
        private static string GetTimeAgo(DateTime dateTime)
        {
            var timeSpan = DateTime.UtcNow - dateTime;

            if (timeSpan.TotalSeconds < 60)
                return "just now";

            if (timeSpan.TotalMinutes < 60)
                return $"{(int)timeSpan.TotalMinutes} minute{((int)timeSpan.TotalMinutes == 1 ? "" : "s")} ago";

            if (timeSpan.TotalHours < 24)
                return $"{(int)timeSpan.TotalHours} hour{((int)timeSpan.TotalHours == 1 ? "" : "s")} ago";

            if (timeSpan.TotalDays < 7)
                return $"{(int)timeSpan.TotalDays} day{((int)timeSpan.TotalDays == 1 ? "" : "s")} ago";

            if (timeSpan.TotalDays < 30)
                return $"{(int)(timeSpan.TotalDays / 7)} week{((int)(timeSpan.TotalDays / 7) == 1 ? "" : "s")} ago";

            if (timeSpan.TotalDays < 365)
                return $"{(int)(timeSpan.TotalDays / 30)} month{((int)(timeSpan.TotalDays / 30) == 1 ? "" : "s")} ago";

            return $"{(int)(timeSpan.TotalDays / 365)} year{((int)(timeSpan.TotalDays / 365) == 1 ? "" : "s")} ago";
        }
    }
}