using System.Text.Json.Serialization;

namespace Talentree.Service.DTOs.AI.HelpCenter
{
    /// <summary>
    /// Response payload returned by the AI Help Center chat endpoint.
    /// </summary>
    public class ChatResponseDto
    {
        /// <summary>
        /// The reply text generated by the AI model.
        /// </summary>
        [JsonPropertyName("reply")]
        public string Reply { get; set; } = string.Empty;
    }
}
