using System.Threading.Tasks;
using Talentree.Service.DTOs.AI.HelpCenter;

namespace Talentree.Service.Contracts
{
    /// <summary>
    /// Service contract for interacting with the AI Help Center chatbot API.
    /// </summary>
    public interface IAiHelpCenterService
    {
        /// <summary>
        /// Forwards user messages to the external AI Help Center service and returns the generated reply.
        /// </summary>
        /// <param name="dto">The chat request payload containing conversation history.</param>
        /// <returns>The reply generated by the AI Help Center.</returns>
        Task<ChatResponseDto> SendChatAsync(ChatRequestDto dto);
    }
}
