name: Deploy Web API to Monster ASP

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Deploy to MonsterASP via WebDeploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'talentree-api' 
        publish-profile: ${{ secrets.DOTNET_PUBLISH_PROFILE }}